// action types
const API_CALL_REQUEST = "API_CALL_REQUEST";
const API_CALL_SUCCESS = "API_CALL_SUCCESS";
const API_CALL_FAILURE = "API_CALL_FAILURE";
const API_FETCH_DATA = "API_FETCH_DATA";

export {
    API_CALL_REQUEST,
    API_CALL_SUCCESS,
    API_CALL_FAILURE,
    API_FETCH_DATA
}
